classdef Config < hive.cfg.ConfigBase
    % configruation information for HIVE treatment '011-008-001-000-000'
    % 
    % this code was generated by scala
    
    % 
    % treatment definition
    % 
    properties (Constant)
        name = '011-008-001-000-000'
        trainingSetId = 11
        trainingStyleId = 8
        clusterStyleId = 1
        alphaSelectId = 0
        muSelectId = 0
    end
    
    % 
    % treatment directories
    % 
    properties (Constant)
        projectHome = '/data/hnl/iterate'
        trainingHome = '/data/hnl/iterate/results_011'
        testingHome = '/data/hnl/iterate/results_011'
        modelHome = '/data/hnl/iterate/results_011/model_style_008'
        clusterHome = '/data/hnl/iterate/results_011/model_style_008/cluster_style_001'
        alphaHome = '/data/hnl/iterate/results_011/model_style_008/cluster_style_001/alpha_select_000'
        muHome = '/data/hnl/iterate/results_011/model_style_008/cluster_style_001/alpha_select_000/mu_select_000'
        codePath = {'/System/Volumes/Data/data/git/hive-config.git'}
    end
    
    % 
    % catalogs
    % 
    properties (Constant)
        training = hive.cfg.TrainingCatalog
        testing = hive.cfg.TestingCatalog
        target = hive.cfg.TargetCatalog
    end
    
    % 
    % methods
    % 
    methods (Static)
        function self = init()
            % INIT initializes the path and returns this config object
            
            self = Config();
            addpath(self.codePath{:}, '-begin');
            fprintf('initialized configuration for %s\n', self.name);
        end
        
    end
    
end
