function text = logPerformance(name, P)
%LOGPERFORMANCE Summary of this function goes here
%   Detailed explanation goes here
    
    text = sprintf('%s,%s,%d,%0.1f,%0.1f,%0.4f,%0.1f,%0.1f,%0.4f\n',...
        name,...
        P.Chem.name,...
        P.Summary.Fit.NumObservations,...
        rms(P.Noise),...
        snr(P.Y, P.Noise),...
        P.Summary.Fit.Rsquared.Ordinary,...
        P.Summary.Fit.RMSE,...
        P.Summary.Fit.Coefficients.Estimate(1),...
        P.Summary.Fit.Coefficients.Estimate(2));
end

