package org.hnl.hive.cfg.matlab

import org.hnl.matlab._
import org.hnl.matlab.M._

/**
 * Chem
 * <p>
 * Created on Mar 1, 2016.
 * <p>
 *
 * @author Jason White
 */
case class Chem(ix: Int, colName: String, name: String, label: String, units: String, neutral: Double) extends Ordered[Chem] {

  def compare(that: Chem): Int = this.ix compare that.ix

}

// scalastyle:off multiple.string.literals

/**
 * ChemClass
 * <p>
 * Created on Mar 1, 2016.
 * <p>
 *
 * @author Jason White
 */
case class ChemClass(chems: List[Chem], treatment: String) extends MatlabChunk with MatlabFormatting {

  /*
   * enumeration
   */
  protected val enum =
    ClassEnum()
      .%(
        "",
        "Valid chemicals for this treatment",
        ""
      )
      .members(chems.sorted.map { c => Fn(c.name, c.ix) })

  /*
   * methods
   */
  protected val methods = {
    // variables used below, for convenience
    val self = v"self"
    val s = v"s"
    val ix = v"ix"
    val a = v"a"
    val n = v"n"
    val d = v"d"

    ClassMethods()
      .+(
        FnDef("ix", self).returns(n)
          .doc("IX returns the index of this Chem")
          .+(
            n =: Fn("uint32", self)
          ),
        FnDef("colName", self).returns(s)
          .doc("COLNAME returns the column name of this Chem")
          .+(
            Persistent(a),
            a %=% RCell(chems.sorted.map { c => Str(c.colName) }: _*),
            s %=% a.curly(self ~> ix)
          ),
        FnDef("name", self).returns(s)
          .doc("NAME returns the name of this Chem")
          .+(
            s %=% Fn("char", self)
          ),
        FnDef("label", self).returns(s)
          .doc("LABEL returns the label of this Chem")
          .+(
            Persistent(a),
            a %=% RCell(chems.sorted.map { c => Str(c.label) }: _*),
            s %=% a.curly(self ~> ix)
          ),
        FnDef("units", self).returns(s)
          .doc("UNITS returns the units of this Chem")
          .+(
            Persistent(a),
            a %=% RCell(chems.sorted.map { c => Str(c.units) }: _*),
            s %=% a.curly(self ~> ix)
          ),
        FnDef("neutral", self).returns(n)
          .doc("NEUTRAL returns the neutral concentration of this Chem")
          .+(
            Persistent(a),
            a %=% RVec(chems.sorted.map { c => Num(c.neutral) }: _*),
            n %=% a.paren(self ~> ix)
          )
      )
  }

  /*
   * class
   */
  protected val mClass =
    ClassDef("Chem").from("uint32", "ChemBase")
      .%(
        s"Chemicals for use in HIVE treatment '$treatment'",
        "",
        "It is convenient to subclass uint32 so that the chemical literals can be",
        "used as an index into a matrix, but we can't add properties to uint32.",
        "",
        "Therefore, we will add methods that perform lookups into persistent arrays",
        "which hold the properties for each chemical literal.",
        "",
        "This code was generated by scala."
      )
      .+(
        enum,
        methods
      )

  def toMatlab: String = mClass.toMatlab
}
