package org.hnl.hive.cfg.matlab

import org.hnl.hive.cfg.InvitroDataset
import org.hnl.hive.cfg.TreatmentConfig
import org.hnl.matlab.M._
import org.hnl.matlab.MExp
import org.hnl.matlab.MExp._

/**
 * TestingCatalog
 * <p>
 * Created on Mar 8, 2016.
 * <p>
 *
 * @author Jason White
 */
case class TestingCatalog(name: String, cfg: TreatmentConfig) extends MatClassFile {

  override val pkg = "hive.cfg"

  protected val paths =
    ClassProps().attribs("Constant") // scalastyle:ignore multiple.string.literals
      .%(
        "",
        "testing paths",
        ""
      )
      .+(
        'sourceSpecList %=% CCell(cfg.testing.sourceSpecs: _*),
        'resultPathList %=% CCell(cfg.testing.resultPaths: _*)
      )

  protected val settings =
    ClassProps().attribs("Constant")
      .%(
        "",
        "settings",
        ""
      )
      .+(
        'vgramFile %=% cfg.testing.vgramFile,
        'metaFile %=% cfg.testing.metaFile,
        'labelFile %=% cfg.testing.labelFile,
        'characterizationFile %=% cfg.testing.characterizationFile,
        'predictionFile %=% cfg.testingPredicitonFile,
        'vgramWindowList %=% CCell(cfg.testing.vgramWindows.map(l => RVec(l: _*)): _*),
        'timeWindowList %=% CCell(cfg.testing.timeWindows.map(l => RVec(l: _*)): _*)
      )

  protected val catalogs =
    ClassProps().attribs("Constant")
      .%(
        "",
        "catalogs",
        ""
      )
      .+(
        'labelCatalogFile %=% cfg.testing.labelCatalogFile,
        'sourceCatalog %=% makeIndexedCellArray(cfg.testing.sourceCatalog)((s: String) => Str(s)),
        'datasetCatalog %=% makeIndexedCellArray(cfg.testing.datasetCatalog)((s: String) => Str(s)),
        'infoCatalog %=% makeIndexedCellArray(cfg.testing.infoCatalog)((x: Option[InvitroDataset]) => x match {
          case Some(ds) => Fn("hive.cfg.InvitroDataset", ds.dsDate, ds.dsClass, ds.dsProtocol, ds.probeName, ds.probeDate)
          case None     => RVec()
        })
      )

  override val mClass =
    ClassDef(name).from("hive.cfg.CatalogBase")
      .%(
        s"testing catalog for HIVE treatment '${cfg.name}'",
        "",
        "this code was generated by scala"
      )
      .+(
        paths,
        settings,
        catalogs
      )
}
