package org.hnl.hive.cfg.matlab

import org.hnl.hive.cfg.TreatmentConfig
import org.hnl.matlab.M._
import org.hnl.matlab.MExp
import org.hnl.matlab.MExp._

/**
 * TestingCatalog
 * <p>
 * Created on Mar 8, 2016.
 * <p>
 *
 * @author Jason White
 */
case class TestingCatalog(name: String, cfg: TreatmentConfig) extends MatClassFile {

  override val mClass =
    ClassDef(name)
      .%(
        s"testing catalog for HIVE treatment '${cfg.name}'",
        "",
        "this code was generated by scala"
      )
      .+()

  override def toMatlab: String = mClass.toMatlab
}
