package org.hnl.hive.cfg.matlab

import org.hnl.hive.cfg.TreatmentConfig
import org.hnl.matlab.M._
import org.hnl.matlab.MExp
import org.hnl.matlab.MExp._

/**
 * TrainingCatalog
 * <p>
 * Created on Mar 8, 2016.
 * <p>
 *
 * @author Jason White
 */
case class TrainingCatalog(name: String, cfg: TreatmentConfig) extends MatClassFile {

  override val pkg = "hive.cfg"

  protected val paths =
    ClassProps().attribs("Constant")
      .%(
        "",
        "training directories",
        ""
      )
      .+(
        'sourceSpecList %=% CCell(cfg.trainingSourceSpecs: _*),
        'resultPathList %=% CCell(cfg.trainingResultPaths: _*)
      )

  protected val catalogs =
    ClassProps().attribs("Constant")
      .%(
        "",
        "catalogs",
        ""
      )
      .+(
        'sourceCatalog %=% makeIndexedCellArray(cfg.trainingSourceCatalog)((s: String) => Str(s)),
        'datasetCatalog %=% makeIndexedCellArray(cfg.trainingDatasetCatalog)((s: String) => Str(s))
      )

  override val mClass =
    ClassDef(name).from("hive.cfg.CatalogBase")
      .%(
        s"training catalog for HIVE treatment '${cfg.name}'",
        "",
        "this code was generated by scala"
      )
      .+(
        paths,
        catalogs
      )
}
