package org.hnl.hive.cfg.matlab

import org.hnl.hive.cfg.TreatmentConfig
import org.hnl.matlab.M._
import org.hnl.matlab.MExp
import org.hnl.matlab.MExp._

/**
 * TrainingCatalog
 * <p>
 * Created on Mar 8, 2016.
 * <p>
 *
 * @author Jason White
 */
case class TrainingCatalog(name: String, cfg: TreatmentConfig) extends MatClassFile {

  override val pkg = "hive.cfg"

  protected val paths =
    ClassProps().attribs("Constant") // scalastyle:ignore multiple.string.literals
      .%(
        "",
        "training directories",
        ""
      )
      .+(
        'sourceSpecList %=% CCell(cfg.training.sourceSpecs: _*),
        'resultPathList %=% CCell(cfg.training.resultPaths: _*)
      )

  protected val settings =
    ClassProps().attribs("Constant")
      .%(
        "",
        "settings",
        ""
      )
      .+(
        'vgramFile %=% cfg.training.vgramFile,
        'metaFile %=% cfg.training.metaFile,
        'labelFile %=% cfg.training.labelFile,
        'characterizationFile %=% cfg.training.characterizationFile,
        'vgramWindowList %=% CCell(cfg.training.vgramWindows.map(l => RVec(l: _*)): _*),
        'timeWindowList %=% CCell(cfg.training.timeWindows.map(l => RVec(l: _*)): _*)
      )

  protected val catalogs =
    ClassProps().attribs("Constant")
      .%(
        "",
        "catalogs",
        ""
      )
      .+(
        'labelCatalogFile %=% cfg.training.labelCatalogFile,
        'sourceCatalog %=% makeIndexedCellArray(cfg.training.sourceCatalog)((s: String) => Str(s)),
        'datasetCatalog %=% makeIndexedCellArray(cfg.training.datasetCatalog)((s: String) => Str(s))
      )

  override val mClass =
    ClassDef(name).from("hive.cfg.CatalogBase")
      .%(
        s"training catalog for HIVE treatment '${cfg.name}'",
        "",
        "this code was generated by scala"
      )
      .+(
        paths,
        settings,
        catalogs
      )
}
