classdef (Abstract) ChemBase
    % Chemicals for use in HIVE treatment 'testing'
    % 
    % It is convenient to subclass uint32 so that the chemical literals can be
    % used as an index into a matrix, but we can't add properties to uint32.
    % 
    % Therefore, we will add methods that perform lookups into persistent arrays
    % which hold the properties for each chemical literal.
    % 
    % This code was generated by scala.
    
    methods (Static)
        function n = count()
            n = length(enumeration('Chem'));
        end
        
        function c = get(x)
            [m, s] = enumeration('Chem');
            
            if isnumeric(x)
                try
                    c = m(x);
                catch ME
                    error('hive:Chem', 'Chemical not found for index %d', x);
                end
            elseif ischar(x)
                c = m(find(strcmp(s, x), 1, 'first'));
                if isempty(c)
                    error('hive:Chem', 'Chemical not found for name "%s"', x);
                end
            end
        end
        
    end
    
end
