%% config hive
%!./make-config /data/hnl/iterate/results_103/100-full.conf
!./make-config treatment-burst.conf

%% init
restoredefaultpath;
clear RESTOREDEFAULTPATH_EXECUTED;
clc;
cfg = Config.init();

addpath(fullfile(pwd, 'lib', 'glmnet_interface'));
addpath(fullfile(pwd, 'testing'));

overwrite = false;
parallel = true;
R2017a = strcmp(version('-release'), '2017a');

if parallel
    gcp();
end

%% import
t = tic;
jitterCorrector = hive.proc.invitro.JitterCorrector()...
    .withExamWindow(1:30);

hive.proc.train.Importer(cfg)...
    .inParallel(parallel)...
    .withOverwrite(overwrite)...
    .withJitterCorrector(jitterCorrector)...
    .purgeExcludedData()...
    .process();
toc(t);

t = tic;
hive.proc.test.Importer(cfg)...
    .inParallel(parallel)...
    .withOverwrite(overwrite)...
    .withJitterCorrector(jitterCorrector)...
    .purgeExcludedData()...
    .process();
toc(t);


%% summarize
t = tic;
hive.proc.train.Summarizer(cfg)...
    .withOverwrite(overwrite)...
    .process()...
    .plot();
toc(t);

t = tic;
hive.proc.test.Summarizer(cfg)...
    .withOverwrite(overwrite)...
    .process()...
    .plot();
toc(t);


%% run cross-validation analyses
% crossvalidate(cfg, 125, 0, 4500);
hive.proc.invitro.Crossvalidator(cfg)...
    .withJitterRemoval(true)...
    .inParallel(parallel && ~R2017a)... % to avoid licence issue with R2017a
    .withOverwrite(overwrite)...
    .withTrainingPercent(125)...
    .withMinimum(0)...
    .withMaximum(4500)...
    .process()...
    .summarize();